<h1>Numpy Problems</h1>



In [1]:
import numpy as np

1. Write a Python Program to convert a list of numeric value into a one-dimensional Numpy array.

In [2]:
num_list = [12.53 , 13.32 , 100.00 , 36.32]
num_array = np.array(num_list)
print(num_array)

[ 12.53  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10

In [3]:
matrix = np.arange(2,11).reshape(3,3)
print(matrix )

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program  to create a nnnnull  vector of  size  10  and update  sixth  value  to 11

In [5]:
null_vector = np.zeros(10)
print(null_vector)
null_vector[5] = 11
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Write a Python program to reverse an array.

In [7]:
num_list = np.array([12 , 13 , 14 , 15 , 16 , 17 , 18 , 19 , 20 , 21 , 22 , 23 , 24 , 25 , 26 , 27 , 28 , 29 , 30 , 31 , 32 , 33 , 34 , 35 , 36 , 37])
reverse_array = num_list[::-1]
print(reverse_array)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2D array with 1 on the border and 0 inside.

In [11]:
matrix = np.ones((5 , 5) , dtype = int)
print(matrix)
print()
matrix[1:-1 , 1:-1] = 0
print(matrix)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


6. Write a Python program to add to border (filled with 0's) around an existing array.

In [14]:
original_matrix = np.ones((3 , 3), dtype = int)
print(original_matrix)
print()
new_matrix = np.pad(original_matrix , pad_width = 1 , mode = "constant" , constant_values = 0)
print(new_matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


7.   Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [16]:
original_matrix = np.zeros((8,8), dtype = int)
print(original_matrix)

print()

original_matrix[1::2 , ::2] = 1
original_matrix[::2 , 1::2] = 1
print(original_matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Program to covert a list and tuple into arrays.


In [17]:
num_list = [1 , 2 , 3 , 4 , 5 , 6 , 7 , 8]
num_array = np.array(num_list)
print(num_array)

print()

num_tuple = ((8 , 4 , 6) , (1 , 2 , 3))
num_array = np.array(num_tuple)
print(num_array)

[1 2 3 4 5 6 7 8]

[[8 4 6]
 [1 2 3]]


9. Write a Python program to append to the end of an array.

In [18]:
original_array = np.array([10 , 20 , 30])
print(original_array)

print()

new_array = np.append(original_array , [40 , 50 , 60 , 70 , 80 ,90])
print(new_array)

[10 20 30]

[10 20 30 40 50 60 70 80 90]


10. Write a Python Program to find the real and imaginary parts of an array of complex numbers.

In [26]:
original_array = np.array([1.265498150+0.5623j , 0.70710678+0.70710678j])
print(original_array)
print()

real_part = original_array.real
imaginary_part = original_array.imag

print(real_part)
print(imaginary_part)


[1.26549815+0.5623j     0.70710678+0.70710678j]

[1.26549815 0.70710678]
[0.5623     0.70710678]


11. Write a Python Program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [27]:
original_array = np.array([1 , 2 , 3] , dtype = np.int64)

size = original_array.size
item_size = original_array.itemsize
total_bytes = original_array.nbytes

print(f"Size of the array : {size}")
print(f"Length of one array element in bytes : {item_size}")
print(f"Total bytes consumed by the elements of the array : {total_bytes}")

Size of the array : 3
Length of one array element in bytes : 8
Total bytes consumed by the elements of the array : 24


12. Write a Python program to find common values between two arrays.

In [30]:
array1 = np.array([0 , 10 , 20 , 30 , 40 , 60])
array2 = np.array([10, 30 , 40])

common_values = np.intersect1d(array1 , array2)

print(array1)
print(array2)
print("Common values between two arrays:")
print(common_values)

[ 0 10 20 30 40 60]
[10 30 40]
Common values between two arrays:
[10 30 40]


13. Write a Python program to find the set difference of two arrays. The set difference will return the sorted. unique values in array1 that are not in array2.

In [31]:
array1 = np.array([0 , 10 , 20 , 40 , 60 , 80])
array2 = np.array([10 , 30 , 40 , 50 , 70 , 90])

set_diff = np.setdiff1d(array1 , array2)

print(array1)
print(array2)
print("Set difference between two arrays:")
print(set_diff)

[ 0 10 20 40 60 80]
[10 30 40 50 70 90]
Set difference between two arrays:
[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.

In [32]:
array1 = np.array([0 , 10 , 20 , 40 , 60 , 80])
array2 = np.array([10 , 30 , 40 , 50 , 70])

unique_value = np.setxor1d(array1 , array2)

print(array1)
print(array2)
print("Unique values that are in only one (not both) of the inputs arrays:")
print(unique_value)

[ 0 10 20 40 60 80]
[10 30 40 50 70]
Unique values that are in only one (not both) of the inputs arrays:
[ 0 20 30 50 60 70 80]


15. Write a Python program to compare two arrays using numpy.


In [34]:
a = np.array([1, 2])
b = np.array([4, 5])

print("Array a:", a)
print("Array b:", b)

print("\na > b")
print(a > b)

print("a >= b")
print(a >= b)

print("a < b")
print(a < b)

print("a <= b")
print(a <= b)


Array a: [1 2]
Array b: [4 5]

a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


16. Write a Python program to save a NumPy array to text file.

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt("array.txt", arr, fmt="%d")  
print("Array saved to 'array.txt'")

Array saved to 'array.txt'


17. Write a Python program to create a contiguous flattened array.

In [37]:
array = np.array([[10 , 20 ,30] , [20 , 40 , 60]])
flattened = array.flatten()

print(array)
print(flattened)

[[10 20 30]
 [20 40 60]]
[10 20 30 20 40 60]


18. Write a Python program to change the data type of an array.

In [39]:
array = np.array([[2,4,6] , [6,8,10]] , dtype = np.int32)
print(array)
print("Data type of the array is: ",array.dtype)

new_array = array.astype(np.float64)
print("New Type: ",new_array.dtype)
print(new_array)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array is:  int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


19. Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [40]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


20. Write a Python program to create an array which looks like below array.

In [51]:
array = np.zeros((4,3))
for i in range (1,4):
    for j in range(i):
        array[i][j] = 1
print(array)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


21. Write a Python program to concatenate two 2-dimensional arrays.

In [52]:
arrar1 = np.array([[0, 1, 3], [5, 7, 9]])
arrar2 = np.array([[0, 2, 4], [6, 8, 10]])

concat_array = np.hstack((array1, array2))
print(concat_array)

[ 0 10 20 40 60 80 10 30 40 50 70]


22. Write a Python program to make an array immutable(read-only).


In [66]:
array = np.array([1, 2, 3])
array.flags.writeable = False


23. Write a Python program to create an array of (3,4) shape , multiple every element value by 3 and display new array.

In [54]:
arr = np.arange(12).reshape(3, 4)
new_arr = arr * 3

print(arr)
print()
print(new_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


24. Write a Pytho program to convert a NumPy array into Python list structure. 

In [56]:
array = np.array([[0, 1], [2, 3], [4, 5]])
list_array = array.tolist()

print(array)
print("Array to list:")
print(list_array)

[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


25. Write a Python  program to  convert a NumPy array into Python list structure.

In [57]:
original_array = np.array([ 0.26153123 , 0.52760141 , 0.5718299 , 0.5927067 , 0.7831874 , 0.69746349
, 0.35399976 , 0.99469633 , 0.0694458 , 0.54711478])
round_off = np.round(original_array , 3)

print(original_array)
print()
print(round_off)

[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


26. Write Python program to suppresses the use of scientific notation for small numbers in numpy array.

In [60]:
original_array = np.array([1.60000000e-10 , 1.60000000e+00 , 1.20000000e+03 , 2.35000000e-01])
np.set_printoptions(suppress=True, precision=3)
print(original_array)

[   0.       1.6   1200.       0.235]


27. Write a Python progrma to how to add an extra column to an numpy array.

In [62]:
array = np.array([[10, 20, 30], [40, 50, 60]])
new_col = np.array([[100], [200]])  

new_array = np.hstack((array, new_col))  

print(new_array)

[[ 10  20  30 100]
 [ 40  50  60 200]]


28. Write a Python program to remove specific elements in a numpy array.

In [64]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
indices_to_delete = [0, 3, 4]
new_array = np.delete(arr, indices_to_delete)
print(array)
print(new_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 20  30  60  70  80  90 100]
